using System.Text;
using System.Text.Json;

namespace Eudiplo.Client;

/// <summary>
/// Key-chain management (access-certificate and document-signer-certificate lifecycle). The
/// private key is generated by EUDIPLO and stays there; callers only read the public key (or
/// export it server-side for manual signing) and later attach an externally-issued
/// certificate.
/// </summary>
public partial class EudiploApiClient
{
    /// <summary>Lists access key-chains (usageType=access) as (Id, Description) — useful for
    /// letting a user pick which access cert should sign a given artifact (e.g. schema
    /// metadata), i.e. the one registered with a registrar.</summary>
    public async Task<IReadOnlyList<(string Id, string Description)>> GetAccessKeyChainsAsync(CancellationToken ct = default)
    {
        using var resp = await SendWithAuthAsync(
            () => new HttpRequestMessage(HttpMethod.Get, "/api/key-chain"), ct);
        if (!resp.IsSuccessStatusCode) return Array.Empty<(string, string)>();
        using var doc = JsonDocument.Parse(await resp.Content.ReadAsStringAsync(ct));
        var root = doc.RootElement;
        var arr = root.ValueKind == JsonValueKind.Array ? root
            : root.TryGetProperty("items", out var it) ? it : default;
        if (arr.ValueKind != JsonValueKind.Array) return Array.Empty<(string, string)>();

        var list = new List<(string, string)>();
        foreach (var e in arr.EnumerateArray())
            if (e.TryGetProperty("usageType", out var u) && u.GetString() == "access"
                && e.TryGetProperty("id", out var i) && i.GetString() is { Length: > 0 } id)
                list.Add((id, e.TryGetProperty("description", out var d) ? d.GetString() ?? id : id));
        return list;
    }

    /// <summary>
    /// Creates a key-chain (EUDIPLO generates the key pair). Returns the raw JSON body of the
    /// created resource (including its id), or throws on failure.
    /// </summary>
    public async Task<string> CreateKeyChainAsync(string usageType, string type, string? description, CancellationToken ct = default)
    {
        var body = JsonSerializer.Serialize(new { usageType, type, description });
        using var resp = await SendWithAuthAsync(
            () => new HttpRequestMessage(HttpMethod.Post, "/api/key-chain")
            {
                Content = new StringContent(body, Encoding.UTF8, "application/json"),
            }, ct);
        var text = await resp.Content.ReadAsStringAsync(ct);
        if (!resp.IsSuccessStatusCode)
            throw new InvalidOperationException($"EUDIPLO key-chain create: HTTP {(int)resp.StatusCode} {text}");
        return text;
    }

    /// <summary>
    /// Exports a key-chain (GET /api/key-chain/{id}/export) in config-import format — includes
    /// the <c>key</c> JWK (including the private <c>d</c> component). Server-side use only; the
    /// private part must never reach a frontend or be persisted anywhere else. GET
    /// /api/key-chain/{id} does not return x/y, hence this export call.
    /// </summary>
    public async Task<string?> ExportKeyChainAsync(string id, CancellationToken ct = default)
    {
        using var resp = await SendWithAuthAsync(
            () => new HttpRequestMessage(HttpMethod.Get, $"/api/key-chain/{id}/export"), ct);
        if (!resp.IsSuccessStatusCode) return null;
        return await resp.Content.ReadAsStringAsync(ct);
    }

    /// <summary>Lists key-chains, optionally filtered by usageType (e.g. "attestation") — for
    /// document-signer certs: GET /api/key-chain already returns the parsed public
    /// activeCertificate (subject/issuer/validity) per entry, no export/PEM parsing needed.</summary>
    public async Task<IReadOnlyList<JsonElement>> GetKeyChainsAsync(string? usageType = null, CancellationToken ct = default)
    {
        using var resp = await SendWithAuthAsync(
            () => new HttpRequestMessage(HttpMethod.Get, "/api/key-chain"), ct);
        if (!resp.IsSuccessStatusCode) return Array.Empty<JsonElement>();
        using var doc = JsonDocument.Parse(await resp.Content.ReadAsStringAsync(ct));
        var root = doc.RootElement;
        var arr = root.ValueKind == JsonValueKind.Array ? root
            : root.TryGetProperty("items", out var it) ? it : default;
        if (arr.ValueKind != JsonValueKind.Array) return Array.Empty<JsonElement>();

        var list = new List<JsonElement>();
        foreach (var e in arr.EnumerateArray())
        {
            if (usageType is not null && (!e.TryGetProperty("usageType", out var u) || u.GetString() != usageType)) continue;
            list.Add(e.Clone());
        }
        return list;
    }
}
